---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chatapp-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: chatapp-dev
  chart:
    git: git@github.com:areshka515/chatconfig
    path: helmapp
    ref: master
  values:
    image:
      repository: eu.gcr.io/intense-pixel-314120/chat
      tag: dev-a760a2
    replicaCount: 1
