apiVersion: v1
kind: Service
metadata:
  name: chatapp
spec:
  selector:
    app: chatapp
  #clusterIP: None
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  #type: LoadBalancer