apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database
spec:
  selector:
    app: mysql
  clusterIP: None
  #type: LoadBalancer
  #ports:
  #- protocol: TCP
  #  port: 3306
  #  targetPort: 3306
  #type: LoadBalancer