apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: database
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch