apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-elasticsearch
  labels:
    app: fluentd-elasticsearch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-elasticsearch
subjects:
- kind: ServiceAccount
  name: fluentd-elasticsearch
  namespace: default
roleRef:
  kind: ClusterRole
  name: fluentd-elasticsearch
  apiGroup: ""

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: fluentd-elasticsearch
      containers: 
      - name: fluentd-elasticsearch
        image: k8s.gcr.io/fluentd-elasticsearch:v2.4.0
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q

        volumeMounts:
        - name: varlog
          mountPath: /var/log
          
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true

        - name: config-volume
          mountPath: /etc/fluent/config.d

        #terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
          
      - name: config-volume
        configMap:
          name: fluentd-elasticsearch-config