apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "chatapp"
spec:
  acme:
    email: "arikn97@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: echo-key
    solvers:
    - http01:
        ingress:
          class: "nginx"